# Constantes:

HTTP_STATUS_OK = 200

# Conexão com o Oracle:
ORACLE_USERNAME = 'IMPAR_PERRELLI'
ORACLE_PASSWORD = 'jun_2021'
ORACLE_SERVER_IP = '10.10.10.211'
ORACLE_SERVER_PORT = '1521'
ORACLE_SID = 'TESTE'

# IMPAR_PERRELLI@//10.10.10.211:1521/TESTE
SQLALCHEMY_DATABASE_URL = f'oracle://{ORACLE_USERNAME}:{ORACLE_PASSWORD}@//{ORACLE_SERVER_IP}:{ORACLE_SERVER_PORT}/' \
                          f'{ORACLE_SID}'
